### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by kfarnung** [kfarnung/puzzle-lib#4]
Starting a list to track things I'd like to add to the library:
- [x] Morse
- [x] Braille
- [x] Caesar cipher - #13
- [x] Character conversions (ordinal/ASCII/binary/ternary) - #15 
- [x] Semaphore - #17 
- [ ] Pigpen
- [ ] Resistor colors
- [ ] Rainbow colors
- [ ] Naval signal flags
- [ ] NATO alphabet
- [ ] Color wheel/mixing
- [x] Number to letter converter [[source](https://github.com/kfarnung/puzzle-lib/issues/4#issuecomment-381382231)] - #30 
- [ ] Phone number to text letter suggestions [[source](https://github.com/kfarnung/puzzle-lib/issues/4#issuecomment-383357765)]

**Comment by kfarnung** [comment]
@sjenks expressed interest in implementing semaphore.

**Comment by kfarnung** [comment]
Thanks @sjenks for #17!

**Comment by sjenks** [comment]
Another wishlist item:
An automatic converter.  Type in "8 5 12 12 15" and prints "Hello".  Type in "72 73" Prints "Hi"
The initial version could probably handle numbers based on ranges

**Comment by beckbria** [comment]
Proposal: Phone to text letter suggestions.

**Comment by kfarnung** [comment]
Opened separate issues to track the rest of the suggestions.
